### ISSUE TITLE
ModuleNotFoundError: No module named 'audio_dataloader'

### ISSUE THREAD

**Issue by kazi-m22** [IntelLabs/IntelNeuromorphicDNSChallenge#9]
While running train_sdnn.py i see this error. I did not find any audio_dataloader module in the files I downloaded from the repository of IntelNeuromorphicDNSChallenge. How do I get this module? I tried searching online but did not find this module.

**Comment by kazi-m22** [comment]
I missed some files while searching. found the dataloader. never mind..

**Comment by A-Telfer** [comment]
Also had this issue while following the docs

**Comment by Mvk122** [comment]
It's in the root directory of the repository, in the jupytr file, add the following: 
```python
import sys
sys.path.append('/path/to/your/root')
```
